<x-layout>
    <main>
        <x-albums.image-slider
            :images="$album->images"
        />
        <x-albums.image-grid-with-featured
            :images="$album->images"
        />
    </main>
</x-layout>
